In [2]:
#Numpy - Trabalhar com matrizes - ver: http://www.numpy.org/

import numpy as np
a = np.arange(15).reshape(3, 5)

In [3]:
#quantas linhas e quantas colunas
a.shape

(3, 5)

In [4]:
#quantas dimensoes
a.ndim

2

In [5]:
#tipo do dado de cada elemento da matriz
a.dtype.name

'int32'

In [6]:
#tamanho em bytes de cada elemento matriz

4

In [7]:
#total de elementos da matriz
a.size

15

In [8]:
#tipo do objeto
type(a)

numpy.ndarray

In [9]:
#inicializando matrizes

np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [15]:
#Matriz 3 dimensoes e inicializada com valores entre 0..24
c = np.arange(24).reshape(2,3,4)
print (c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [17]:
#operacoes simples de matriz
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

A*B #Esta certo?

array([[2, 0],
       [0, 4]])

In [18]:
A@B

array([[5, 4],
       [3, 4]])

In [22]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [23]:
A+B

array([[3, 1],
       [3, 5]])

In [26]:
B

array([[2, 0],
       [3, 4]])

In [27]:
B.diagonal()

array([2, 4])

In [29]:
B.sum()

9

In [30]:
B.min()

0

In [31]:
B.max()

4

In [32]:
B.cumsum()

array([2, 2, 5, 9], dtype=int32)

In [34]:
import numpy as np
import matplotlib.pyplot as plt

def mandelbrot( h,w, maxit=20 ): 
    """Returns an image of the Mandelbrot fractal of size (h,w)."""
    y,x = np.ogrid[ -1.4:1.4:h*1j, -2:0.8:w*1j ]
    c = x+y*1j
    z = c
    divtime = maxit + np.zeros(z.shape, dtype=int)
    for i in range(maxit):
        z = z**2 + c
        diverge = z*np.conj(z) > 2**2            # who is diverging
        div_now = diverge & (divtime==maxit)  # who is diverging now
        divtime[div_now] = i                  # note when
        z[diverge] = 2                        # avoid diverging too much
    return divtime
plt.imshow(mandelbrot(400,400))
plt.show()

<Figure size 640x480 with 1 Axes>